apiVersion: v1
kind: Namespace
metadata:
    name: MAIA_RESOURCE_NAMESPACE
...

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: MAIA_RESOURCE_NAMESPACE-mywebapp
        image: MINDWAVEREGISTRY/MAIA_RESOURCE_NAMESPACE-mywebapp:v${BUILD_NUMBER}
        ports:
        - containerPort: 80
