apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA_RESOURCE_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp
  namespace: $MAIA_RESOURCE_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp
  template:
    metadata:
      labels:
        app: phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp
    spec:
      containers:
      - name: phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp
        image: ${MINDWAVEREGISTRY}/phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '80'
        - name: HOST
          value: 0.0.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA_RESOURCE_NAMESPACE}-my-webapp
  namespace: $MAIA_RESOURCE_NAMESPACE
spec:
  selector:
    app: phr-${MAIA_RESOURCE_NAMESPACE-my-webapp
  ports:
  - port: 80
