apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-namespace-my-service1 
  namespace: my-namespace # Use the namespace name defined above
spec:
  selector:
    matchLabels:
      app: my-namespace-my-service1
  template:
    metadata:
      labels:
        app: my-namespace-my-service1
    spec:
      containers:
      - name: my-namespace-my-service1
        image: aksdeployment.azurecr.io/my-namespace-my-service1:latest
        env:
        - name: PORT
          value: '80'
        - name: HOST
          value: 0.0.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-namespace-my-service1 
  namespace: my-namespace 
spec:
  selector:
    app: my-namespace-my-service1
  ports:
  - port: 80
