apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-my-service1 
  namespace: sample
spec:
  selector:
    matchLabels:
      app: sample-my-service1
  template:
    metadata:
      labels:
        app: sample-my-service1
    spec:
      containers:
      - name: sample-my-service1
        image: aksdeployment.azurecr.io/sample-my-service1:latest
        env:
        - name: PORT
          value: '80'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-my-service1 
  namespace: sample 
spec:
  selector:
    app: sample-my-service1
  ports:
  - port: 80
