apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA_RESOURCE_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MAIA_RESOURCE_NAMESPACE}-my-service1
  namespace: $MAIA_RESOURCE_NAMESPACE
spec:
  selector:
    matchLabels:
      app: ${MAIA_RESOURCE_NAMESPACE}-my-service1
  template:
    metadata:
      labels:
        app: ${MAIA_RESOURCE_NAMESPACE}-my-service1
    spec:
      containers:
      - name: ${MAIA_RESOURCE_NAMESPACE}-my-service1
        image: ${MINDWAVEREGISTRY}/phr-${MAIA_RESOURCE_NAMESPACE}-my-service1:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '80'
        - name: HOST
          value: 0.0.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ${MAIA_RESOURCE_NAMESPACE}-my-service1
  namespace: $MAIA_RESOURCE_NAMESPACE
spec:
  selector:
    app: ${MAIA_RESOURCE_NAMESPACE-my-service1
  ports:
  - port: 80
