apiVersion: v1
kind: Namespace
metadata:
    name: $MAIA_RESOURCE_NAMESPACE
...

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MAIA_RESOURCE_NAMESPACE}-mywebapp
  namespace: $MAIA_RESOURCE_NAMESPACE 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${MAIA_RESOURCE_NAMESPACE}-mywebapp
  template:
    metadata:
      labels:
        app: ${MAIA_RESOURCE_NAMESPACE}-mywebapp
    spec:
      containers:
      - name: ${MAIA_RESOURCE_NAMESPACE}-mywebapp
        image: ${MINDWAVEREGISTRY}/${MAIA_RESOURCE_NAMESPACE}-mywebapp:v${BUILD_NUMBER}
        ports:
        - containerPort: 80
